Applications/urls.py
from django.urls import  path
from django.conf.urls.static import static
from Applications import views
from django.conf import settings

urlpatterns = [
    path('', views.App,name='apps'),
    path('applications/<int:pk>', views.AppDetail,name='app_detail'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyPortfolio/urls.py
from django.contrib import admin
from django.urls import include, path
import Applications

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Applications.urls')),
]

Applications/models.py
from django.db import models

# Create your models here.

class Application(models.Model):
    CategoriesList= [
    ("Flutter", "Flutter"),
    ("Django", "Django"),
]
    title =models.CharField(max_length=50)
    description = models.TextField()
    category = models.CharField(max_length=50,choices=CategoriesList)
    dateCreated = models.DateTimeField()

    def __str__(self):
        return self.title
    

class Image(models.Model):
    app = models.ForeignKey(Application,on_delete=models.CASCADE)
    img = models.FileField()

Applications/views.py
from django.shortcuts import render
from django.shortcuts import redirect, render
from .models import Application
# Create your views here.

def AppDetail(request,pk):
    application = Application.objects.get(pk=pk)
    context ={'application':application}
    return render(request,'app_detail.html',context)

def App(request):
    applications = Application.objects.all()
    context ={'applications':applications}
    return render(request,'index.html',context)

templates/app_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  
  <!-- Template Main CSS File -->
  <link href="{% static '/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Personal
  * Updated: Jun 18 2023 with Bootstrap v5.3.0
  * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <main id="main">

    <!-- ======= Portfolio Details ======= -->
    <div id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row">

          <div class="col-lg-8">
            <h2 class="portfolio-title">This is an example of portfolio detail</h2>

            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">
                {% for image  in application.image_set.all %}
                <div class="swiper-slide">
                  <img width="100%" src="{{image.img.url}}" alt="">
                </div>              
                {% endfor %}               
              </div>
              <div class="swiper-pagination"></div>
            </div>

          </div>

          <div class="col-lg-4 portfolio-info">
            <h3>{{application.title}}</h3>
            <ul>
              <li><strong>Category</strong>: {{application.title}}</li>
              <li><strong>Project date</strong>: {{application.dateCreated}}</li>
              <li><strong>Project URL</strong>: <a href="#">www.example.com</a></li>
            </ul>

            <p>
              {{application.description}}
            </p>
          </div>

        </div>

      </div>
    </div><!-- End Portfolio Details -->

  </main><!-- End #main -->

  <!-- Vendor JS Files -->
  <script src="{% static '/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static '/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static '/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static '/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static '/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static '/js/main.js' %}"></script>

</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
      
        <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">
      
      
      
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  
  <!-- Template Main CSS File -->
  <link href="{% static '/css/style.css' %}" rel="stylesheet">

</head>

<body>
      <!-- Vendor JS Files -->
  <script src="{% static '/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static '/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static '/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static '/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static '/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static '/js/main.js' %}"></script>
    {% block content %}{% endblock content %}
</body>


</html>